apiVersion: v1
kind: Service
metadata:
  name: register-app-service
spec:
  type: LoadBalancer
  selector:
    app: register-app
  ports:
    - protocol: TCP
      port: 8090        # external port (browser access)
      targetPort: 8080  # containerPort inside pods
